# Generated by Django 5.1.6 on 2025-07-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShadowsocksConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server", models.GenericIPAddressField(default="213.148.10.128")),
                ("port", models.PositiveIntegerField(default=8388)),
                ("password", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(default="chacha20-ietf-poly1305", max_length=50),
                ),
                ("timeout", models.PositiveIntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="XrayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=36, unique=True)),
                ("log_level", models.CharField(default="info", max_length=10)),
                ("vless_port", models.PositiveIntegerField(default=443)),
                ("vless_network", models.CharField(default="ws", max_length=10)),
                ("vless_path", models.CharField(default="/vless", max_length=255)),
                ("shadowsocks_port", models.PositiveIntegerField(default=8388)),
                (
                    "shadowsocks_method",
                    models.CharField(default="chacha20-ietf-poly1305", max_length=50),
                ),
                ("shadowsocks_password", models.CharField(max_length=255)),
                ("wireguard_port", models.PositiveIntegerField(default=51820)),
                ("wireguard_secret_key", models.CharField(max_length=255)),
                ("wireguard_public_key", models.CharField(max_length=255)),
                (
                    "wireguard_address",
                    models.GenericIPAddressField(default="213.148.10.128"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DropboxSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("app_key", models.CharField(max_length=100)),
                ("app_secret", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropbox_settings",
                        to="vpn_management.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_data_used", models.BigIntegerField(default=0)),
                ("last_connection", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="vpn_management.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WireGuardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private_key", models.CharField(max_length=255)),
                ("public_key", models.CharField(max_length=255)),
                (
                    "allowed_ips",
                    models.CharField(default="0.0.0.0/0, ::/0", max_length=255),
                ),
                (
                    "endpoint",
                    models.CharField(default="wg.proanfi.ru:51820", max_length=255),
                ),
                ("dns", models.CharField(default="1.1.1.1", max_length=255)),
                ("persistent_keepalive", models.PositiveIntegerField(default=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wireguard_configs",
                        to="vpn_management.user",
                    ),
                ),
            ],
        ),
    ]
